#Server
server:
  port: 8091

#Spring
spring:

  #Application
  application:
    name: apis-metrobus-service
  
  #Datasource
  datasource:
    url: jdbc:mysql://localhost:3306/metrobus
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: rdn5E1_09dzQ$1&a
  jackson:
    serialization:
      fail-on-empty-beans: false
  #JPA
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
api:
  geocoding:
    uri: https://maps.googleapis.com/maps/api/geocode/json?
    key: key